# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'DreamTeamKadeem' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire', '~> 4.2'
pod 'SwiftyJSON', '~> 3.1'
pod 'EmojiTextView', '~> 1.0'



  # Pods for DreamTeamKadeem

end
